### ISSUE TITLE
Multiple Select Filters on Property

### ISSUE THREAD

**Issue by khixar** [ericziethen/django-property-filter-issue-reporting#8]
Hi there,

I wanted to apply a multiple-choice filter on a related property. Assume there's a `status` property on the model say `Task` which returns an enum. 

From the `filterset_class`, I would like to pass multiple statuses comma-separated or any multi-choice (1, 2, 3) and want to filter out the queryset based on it.

I've been experimenting with different filter options mentioned [here](https://django-property-filter.readthedocs.io/en/stable/ref/filters.html) but the documentation is not very clear on how to use them.

Any help would be appreciated. 

I'm adding a small snippet to give a better idea of what I'm trying to achieve.

Views file:
```
class TaskViewSet(GenericViewSet,):
    queryset = OnboardingTask.objects.all()
    filter_backends = (DjangoFilterBackend,)
    filterset_class = ExecutableTaskFilter
```

Filters file:
```
class ExecutableTaskFilter(PropertyFilterSet):
    status = PropertyMultipleChoiceFilter(
        field_name='task__status',
        lookup_expr='exact',
        choices=EmployeeTaskCategory.choices, // this is the confusing part
    )
```

Property:
```
def status(self):
        delta_days = self.get_due_date_delta_days()
        if delta_days < 0:
            return EmployeeTaskCategory.OVERDUE
        if delta_days <= 7:
            return EmployeeTaskCategory.DUE_WEEK
        return EmployeeTaskCategory.UPCOMING
```

Choices file:
```
class EmployeeTaskCategory(models.IntegerChoices):
    OVERDUE = 1, 'Overdue'
    DUE_WEEK = 2, 'Due in a week'
    UPCOMING = 3, 'Upcoming'
```

**Comment by ericziethen** [comment]
Hi @khixar,

PropertyMultipleChoiceFilter works the same as MultipleChoiceFilter from django-filter (which django-property-filter extends).

In the django-filter documentation https://django-filter.readthedocs.io/en/stable/ref/filters.html#multiplechoicefilter it refers to ChoiceFilter and has an example how to parse the filter at https://django-filter.readthedocs.io/en/stable/ref/filters.html#choicefilter.

The "choices" arguments expect a list of tuples to be passed.

From your example it doesn't look like the tuple is defined.


```
choices=EmployeeTaskCategory.choices, // this is the confusing part

class EmployeeTaskCategory(models.IntegerChoices):
    OVERDUE = 1, 'Overdue'
    DUE_WEEK = 2, 'Due in a week'
    UPCOMING = 3, 'Upcoming'
```

Try converting the your choices into a list of tuples and it should work.

In case you want some more examples of usage you can also have a look at the test examples at [tests/django_property_filter/filters/test_property_multiple_choice_filter.py](https://github.com/ericziethen/django-property-filter/blob/master/tests/django_property_filter/filters/test_property_multiple_choice_filter.py)

**Comment by khixar** [comment]
Thanks for pointing it out. I've one more query related to this. It's related to null values. It'd be great if you can guide me on this as well. 

After updating it to a list of tuples, I'm getting an issue where my related field could potentially be null. So the queryset could contain `null tasks` which could raise an error for the `task__status` property filter. 
```
AttributeError: 'NoneType' object has no attribute 'status'
```
I've looked into [common problems for filters](https://django-filter.readthedocs.io/en/stable/guide/tips.html#filter-and-lookup-expression-mismatch-in-range-isnull) but I think this doesn't serve my use-case.

How do you think this should be tackled?
1. Override `get_queryset` to filter out the null tasks. (not in favor because I could potentially apply the filter here by parsing the query params)
2. Any way to tell the property filter that `task` could be null so ignore if that's the case.

Thanks!

**Comment by ericziethen** [comment]
When you say "task could be null", what do you mean with that? Do you mean tasks doesn't have a status?

I guess the whole filter will be applied against the task table?

Can you give an example including the model definitions and where and how the issue would occur.

**Comment by khixar** [comment]
Thanks for the response. 

Here's the minimal relationship b/w `OnboardingTask` and `EmployeeTask`.

```
class OnboardingTask(models.Model):
    name = models.CharField(max_length=256, null=True, blank=True)
    task: "EmployeeTask" = models.ForeignKey(
        'employee.EmployeeTask',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='+',
    )
``` 

```
class EmployeeTask(models.Model):
    title = models.CharField(max_length=256)

    @cached_property
    def status(self):
        delta_days = self.get_due_date_delta_days()
        if delta_days < 0:
            return EmployeeTaskCategory.OVERDUE
        if delta_days <= 7:
            return EmployeeTaskCategory.DUE_WEEK
        return EmployeeTaskCategory.UPCOMING
```

So I'm trying to apply a filter on `OnboardingTask` related field called `task__status` which is a `EmployeeTask` property, where related field `task: EmployeeTask` could be null being `null=True` on `OnboardingTask` model.

Now those onboarding tasks complain where task is null.

Let me know if you need more info.
Regards,

**Comment by ericziethen** [comment]
Can you also post the actual issue you are seeing? Do you get an exception?
Can you also try the same scenario using MultipleChoiceFilter instead of PropertyMultipleChoiceFilter to see if it behaves differently.

**Comment by khixar** [comment]
Changing it to `MultipleChoiceFilter` didn't work. I believe that would only work for related fields and not properties.
```
class ExecutableTaskFilter(filters.FilterSet):
    status = filters.MultipleChoiceFilter(
        field_name='task__status',
        lookup_expr='exact',
        choices=[(item.value, item.name) for item in EmployeeTaskCategory],
    )

    class Meta:
        model = OnboardingTask
        fields = ('category', 'status')
```

Error:
```
class ExecutableTaskFilter(filters.FilterSet):
    status = filters.MultipleChoiceFilter(
        field_name='task__status',
        lookup_expr='exact',
        choices=[(item.value, item.name) for item in EmployeeTaskCategory],
    )

    class Meta:
        model = OnboardingTask
        fields = ('category', 'status')
```

Error:
```
raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: status
```

the original exception with PropertyFilter is as follows:
```
AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by ericziethen** [comment]
Thanks,

I meant if you choose the filter on a bin property field where the task is also Null, do you also get an exception or what would you see in that case?

**Comment by khixar** [comment]
Still the same exception. I changed it to something like this:
```
class ExecutableTaskFilter(PropertyFilterSet):
    status = PropertyNumberFilter(field_name='task__status', lookup_expr='exact')

    class Meta:
        model = OnboardingTask
        fields = ('category', 'status')
```

Err:
```
AttributeError: 'NoneType' object has no attribute 'status'
```

This API response might help. Here, `status` is null if the task is not created.
```
[{
  "id": 2079,
  "name": "Assign a buddy",
  "is_task_created": false,
  "status": null
},
{
  "id": 2080,
  "name": "Assign a buddy",
  "is_task_created": true,
  "status": 3,
  "is_done": true
}]
```

**Comment by ericziethen** [comment]
Are you able to setup a full minimal example project with some data? Then I can have a look directly and see where it goes wrong.
Ideally an example using 

- PropertyNumberFilter
- NumberFilter

so that I can compare and see if handles that gracefully in django_filter but not in django_property_filter.

**Comment by khixar** [comment]
Yeah, I'll post the working example soon.

**Comment by ericziethen** [comment]
Hi @khixar , 

I have added a fix for this issues where filtering on foreign keys with Null values should not crash anymore.
Can you try with the latest version (1.2.0) and let me know if you are still having this issue
